### ISSUE TITLE
lakinwecker: Space Repetition

### ISSUE THREAD

**Issue by asdfjkl** [asdfjkl/jfxchess#15]
lakinwecker commented 3 hours ago
Would you be interested in features supporting reading opening books (based on loading a complete PGN file for the book) and then allowing annotation of the positions with arrows (saving the annotations) and then allowing for spaced-repetition style learning using a chessboard, with the ability to transition into a game against the computer once you learn a line?

I'd also be interested in adding features allowing you to search for and practice tactics arising out of games that used the opening line you learned.

I know that you have the script which generated anki cards from an opening book - but I wasn't sure if you were interested in adding these features to Jerry directly or not?

**Comment by asdfjkl** [comment]
1.) sorry for deleting your comments - I was merging the old and new repo. and hence your comment was deleted.
2.) If I understand correctly, you would like to add a space repetition functionality to learn openings. I think this is a nice feature, but honestly, to implement this properly is a _huge_ undertaking in my opinion. Basically, one would have to recreate a full "Anki engine" in _addition_ to the chess functionality all within Jerry to get it right. 

So I wonder whether Anki or a standalone tool might be the better place to start and/or fork. And once this becomes mature to merge it into Jerry...

**Comment by lakinwecker** [comment]
Hello, no worries about deleting my comments. Because of that, I didn't receive notices of your comments though, so that is why I am responding so late. :)  

Yes, I am talking about a fairly large undertaking, but it is something that I am very keen on trying to do it. I plan to start soon.  Although I could use Anki - I feel that having this functionality integrated into the same program where you read your chess books could be very powerful.  If you get a move wrong, it could easily open your book to the chapter that studies the line. It could also store any notes or arrows you have related to that position. 

I will start the process of this and will comment back here once I make enough progress so that it is worth sharing.

**Comment by asdfjkl** [comment]
... with chessable and Anki supporting chess, this is not going to happen anymore...
